"use client";
import { useActionState } from "react";
import Link from "next/link";
import { Button } from "@/components/ui/button";
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card";
import { Dialog, DialogContent, DialogDescription, DialogHeader, DialogTitle, DialogTrigger } from "@/components/ui/dialog";
import { Input } from "@/components/ui/input";
import { logoutAction } from "@/features/auth/actions/auth.actions";
import { updateDisplayNameAction, updateSettingsAction, type ProfileActionState } from "@/features/profile/actions/profile-settings.actions";
import type { ProfileSettings } from "@/features/profile/types/profile-settings";
const initial: ProfileActionState = { status: "idle", message: "" };

export function ProfileContent({ data }: { data: ProfileSettings }) { const [state, action, pending] = useActionState(updateDisplayNameAction, initial); return <section className="mx-auto max-w-3xl space-y-8 py-6 sm:py-10"><header><h1 className="text-[length:var(--text-page-title)] font-semibold">Profile</h1><p className="mt-2 leading-7 text-muted-foreground">Your account details and privacy at a glance.</p></header><Card><CardHeader><CardTitle>Your information</CardTitle></CardHeader><CardContent><form action={action} className="space-y-4"><label className="grid gap-2 text-sm font-medium">Display name<Input defaultValue={data.displayName} name="displayName" required /></label><p className="text-sm text-muted-foreground">Email: {data.email}</p><p className="text-sm text-muted-foreground">Onboarding: {data.onboardingComplete ? "Complete" : "Not complete"}</p><Button disabled={pending} fullWidth={false}>{pending ? "Saving…" : "Save name"}</Button><p aria-live="polite" className={state.status === "error" ? "text-sm text-destructive" : "text-sm text-success"}>{state.message}</p></form></CardContent></Card><Card><CardHeader><CardTitle>Privacy</CardTitle></CardHeader><CardContent>Health Decoded stores your profile and private educational progress. Reflections and future AI conversations are private. Your information is not public and is not shared with caregivers.</CardContent></Card><div className="flex flex-wrap gap-3"><Link className="inline-flex min-h-11 items-center rounded-lg px-4 text-sm font-semibold text-primary hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring" href="/settings">Settings</Link><form action={logoutAction}><Button fullWidth={false} variant="secondary">Sign out</Button></form><DeletionInfo /></div></section>; }

function DeletionInfo() { return <Dialog><DialogTrigger className="inline-flex min-h-11 items-center rounded-lg border border-border px-4 text-sm font-semibold text-muted-foreground hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring">Request account deletion</DialogTrigger><DialogContent><DialogHeader><DialogTitle>Account deletion is not available yet</DialogTitle><DialogDescription>A future deletion request will remove your account and private information. This prototype does not delete any data.</DialogDescription></DialogHeader><Button disabled>Deletion unavailable</Button></DialogContent></Dialog>; }

export function SettingsContent({ data }: { data: ProfileSettings }) { const [state, action, pending] = useActionState(updateSettingsAction, initial); return <section className="mx-auto max-w-3xl space-y-8 py-6 sm:py-10"><header><h1 className="text-[length:var(--text-page-title)] font-semibold">Settings</h1><p className="mt-2 leading-7 text-muted-foreground">Choose reading and motion preferences that feel comfortable.</p></header><Card><CardHeader><CardTitle>Accessibility and language</CardTitle></CardHeader><CardContent><form action={action} className="space-y-5"><input name="reducedMotion" type="hidden" value="false" /><label className="flex items-center gap-3"><input defaultChecked={data.reducedMotion} name="reducedMotion" type="checkbox" value="true" /><span>Reduce motion</span></label><label className="grid gap-2 text-sm font-medium">Text size<select defaultValue={data.preferredTextScale} name="preferredTextScale"><option value="default">Standard</option><option value="large">Large</option><option value="extra_large">Extra large</option></select></label><label className="grid gap-2 text-sm font-medium">Language<select defaultValue={data.locale} name="locale"><option value="en">English</option></select></label><label className="grid gap-2 text-sm font-medium">Timezone<Input defaultValue={data.timezone} name="timezone" required /></label><Button disabled={pending} fullWidth={false}>{pending ? "Saving…" : "Save settings"}</Button><p aria-live="polite" className={state.status === "error" ? "text-sm text-destructive" : "text-sm text-success"}>{state.message}</p></form></CardContent></Card><Link className="inline-flex min-h-11 items-center rounded-lg px-3 text-sm font-medium text-primary hover:bg-muted focus-visible:ring-2 focus-visible:ring-ring" href="/profile">Back to profile</Link></section>; }
