export const appointmentQuestionLibrary = [
  ["Understanding", "What are the most important things I should understand?"],
  ["Understanding", "Could you explain that in another way?"],
  ["Understanding", "What should I write down?"],
  ["Understanding", "What should I review after this appointment?"],
  ["Options", "What options should we discuss?"],
  ["Options", "What are the possible benefits and downsides?"],
  ["Options", "What information would help us decide?"],
  ["Options", "Is there anything I should consider before choosing?"],
  ["Medicines", "What is this medicine intended to do?"],
  ["Medicines", "How should I use it?"],
  ["Medicines", "What should I do if I have a concern?"],
  ["Medicines", "Who should I contact with questions?"],
  ["Medicines", "What information should I read or keep?"],
  ["Tests and results", "What is this test for?"],
  ["Tests and results", "How should I prepare?"],
  ["Tests and results", "When and how will I receive the result?"],
  ["Tests and results", "Who will explain the result?"],
  ["Tests and results", "What follow-up may be needed?"],
  ["Daily life", "How should I apply this advice in my daily routine?"],
  ["Daily life", "What should I do when my schedule makes this difficult?"],
  ["Daily life", "Is there someone who can help me practice this?"],
  ["Daily life", "What should I focus on first?"],
  ["Follow-up", "What should happen after this visit?"],
  ["Follow-up", "What should I schedule?"],
  ["Follow-up", "When should I follow up?"],
  ["Follow-up", "Who should I contact if I have questions?"],
  ["Follow-up", "What should I do if I cannot complete the next step?"],
  ["Cost and access", "Is there a lower-cost option we should discuss?"],
  ["Cost and access", "Who can help me understand coverage or cost?"],
  ["Cost and access", "Is there a program or educator who can help?"],
  ["Cost and access", "What should I do if transportation or scheduling is difficult?"],
  ["Who to contact", "Who should I contact if I have questions later?"],
].map(([category, text], index) => ({
  id: `APPT-PREP-QF${String(index + 1).padStart(2, "0")}`,
  category: category!,
  text: text!,
}));
