import type { GlossarySource } from "@/features/glossary/types/medical-glossary";

export const glossarySources: readonly GlossarySource[] = [
  {
    id: "SRC-ADA-TERMS",
    organization: "American Diabetes Association",
    title: "Diabetes-related common terms",
    url: "https://diabetes.org/about-diabetes/common-terms",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-NIDDK-OVERVIEW",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Diabetes overview",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-NIDDK-TESTS",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Diabetes tests and diagnosis",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/tests-diagnosis",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-NIDDK-KIDNEY",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Diabetic kidney disease",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/diabetic-kidney-disease",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-CDC-PLAIN",
    organization: "Centers for Disease Control and Prevention",
    title: "DSMES plain-language glossary",
    url: "https://www.cdc.gov/diabetes-toolkit/php/health-literacy-tool/glossary.html",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-CDC-DSMES",
    organization: "Centers for Disease Control and Prevention",
    title: "Diabetes self-management education and support",
    url: "https://www.cdc.gov/diabetes/education-support-programs/index.html",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-CDC-MENTAL",
    organization: "Centers for Disease Control and Prevention",
    title: "Diabetes and mental health",
    url: "https://www.cdc.gov/diabetes/living-with/mental-health.html",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-FDA-MEDS",
    organization: "U.S. Food and Drug Administration",
    title: "Diabetes medicines",
    url: "https://www.fda.gov/files/for%20consumers/published/Diabetes-Medicines.pdf",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-CMS-TERMS",
    organization: "Centers for Medicare & Medicaid Services",
    title: "Health insurance terms",
    url: "https://www.cms.gov/medical-bill-rights/help/guides/health-insurance-terms",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-HD-LESSONS",
    organization: "Health Decoded",
    title: "Approved learner-facing curriculum glossary content",
    url: "internal://health-decoded/lessons",
    reviewedAt: "2026-08-02",
  },
  {
    id: "SRC-NIDDK-MONOGENIC",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Monogenic diabetes (MODY and neonatal diabetes mellitus)",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/what-is-diabetes/monogenic-neonatal-mellitus-mody",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-CPEPTIDE",
    organization: "National Library of Medicine",
    title: "C-peptide test",
    url: "https://medlineplus.gov/lab-tests/c-peptide-test/",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-CDC-ACTIVITY",
    organization: "Centers for Disease Control and Prevention",
    title: "What counts as physical activity for adults",
    url: "https://www.cdc.gov/physical-activity-basics/adding-adults/what-counts.html",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NHLBI-ATHEROSCLEROSIS",
    organization: "National Heart, Lung, and Blood Institute",
    title: "What is atherosclerosis?",
    url: "https://www.nhlbi.nih.gov/health/atherosclerosis",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-FDA-MEDS-CURRENT",
    organization: "U.S. Food and Drug Administration",
    title: "Women and diabetes: diabetes medicines",
    url: "https://www.fda.gov/consumers/womens-health-topics/women-and-diabetes-diabetes-medicines",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-ADA-INSULIN",
    organization: "American Diabetes Association",
    title: "Insulin basics",
    url: "https://diabetes.org/health-wellness/medication/insulin-basics",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-FDA-INSULIN",
    organization: "U.S. Food and Drug Administration",
    title: "Insulin",
    url: "https://www.fda.gov/consumers/free-publications-women/insulin",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDDK-ISLETS",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Pancreatic islet transplantation",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/insulin-medicines-treatments/pancreatic-islet-transplantation",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-AUTOIMMUNE",
    organization: "National Library of Medicine",
    title: "Autoimmune diseases",
    url: "https://medlineplus.gov/ency/article/000816.htm",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-AUTOANTIBODY",
    organization: "National Library of Medicine",
    title: "Autoantibody testing",
    url: "https://medlineplus.gov/lab-tests/autoantibody-testing/",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-MODY",
    organization: "National Library of Medicine",
    title: "Maturity-onset diabetes of the young",
    url: "https://medlineplus.gov/genetics/condition/maturity-onset-diabetes-of-the-young/",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-DAILYMED-SYMLIN",
    organization: "National Library of Medicine",
    title: "SymlinPen prescribing information",
    url: "https://dailymed.nlm.nih.gov/dailymed/drugInfo.cfm?setid=4aea30ff-eb0d-45c1-b114-3127966328ff",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-ADA-DIAGNOSIS",
    organization: "American Diabetes Association",
    title: "Diabetes diagnosis and tests",
    url: "https://diabetes.org/about-diabetes/diagnosis",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-ADA-LADA",
    organization: "American Diabetes Association",
    title: "Understanding latent autoimmune diabetes in adults",
    url: "https://diabetes.org/about-diabetes/lada",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-NEONATAL",
    organization: "National Library of Medicine",
    title: "Permanent neonatal diabetes mellitus",
    url: "https://medlineplus.gov/genetics/condition/permanent-neonatal-diabetes-mellitus/",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-GLUCOSE",
    organization: "National Library of Medicine",
    title: "Blood glucose test",
    url: "https://medlineplus.gov/lab-tests/blood-glucose-test/",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-CDC-CGM",
    organization: "Centers for Disease Control and Prevention",
    title: "Continuous glucose monitors",
    url: "https://www.cdc.gov/diabetes/treatment/continuous-glucose-monitors.html",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-FDA-ARTIFICIAL-PANCREAS",
    organization: "U.S. Food and Drug Administration",
    title: "What is an artificial pancreas device system?",
    url: "https://www.fda.gov/medical-devices/artificial-pancreas-device-system/what-pancreas-what-artificial-pancreas-device-system",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-ADA-KETONES",
    organization: "American Diabetes Association",
    title: "Managing ketones with diabetes",
    url: "https://diabetes.org/living-with-diabetes/managing-ketones",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDDK-NEUROPATHY",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Peripheral and autonomic neuropathy in diabetes",
    url: "https://www2.niddk.nih.gov/-/media/Files/Strategic-Plans/Diabetes-in-America-3rd-Edition/DIA_Ch23.pdf",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDDK-PROXIMAL-NEUROPATHY",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Proximal neuropathy",
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/nerve-damage-diabetic-neuropathies/proximal-neuropathy",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDDK-CARDIOVASCULAR-RISK",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Addressing cardiovascular risk factors in people with diabetes",
    url: "https://www.niddk.nih.gov/health-information/professionals/diabetes-discoveries-practice/addressing-cardiovascular-risk-factors-in-people-diabetes",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NCBI-DKA",
    organization: "National Library of Medicine",
    title: "Diabetic ketoacidosis",
    url: "https://www.ncbi.nlm.nih.gov/books/NBK620701/",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-MEDLINEPLUS-DIABETES-MEDS",
    organization: "National Library of Medicine",
    title: "Diabetes medicines",
    url: "https://medlineplus.gov/diabetesmedicines.html",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDCR-DIABETES-ORAL-HEALTH",
    organization: "National Institute of Dental and Craniofacial Research",
    title: "Diabetes and oral health",
    url: "https://www.nidcr.nih.gov/health-info/diabetes",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDCR-DRY-MOUTH",
    organization: "National Institute of Dental and Craniofacial Research",
    title: "Dry mouth",
    url: "https://www.nidcr.nih.gov/health-info/dry-mouth",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-CDC-DIABETES-SKIN",
    organization: "Centers for Disease Control and Prevention",
    title: "Diabetes and your skin",
    url: "https://www.cdc.gov/diabetes/signs-symptoms/diabetes-and-your-skin.html",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-CDC-CANDIDIASIS",
    organization: "Centers for Disease Control and Prevention",
    title: "Risk factors for candidiasis",
    url: "https://www.cdc.gov/candidiasis/risk-factors/index.html",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDDK-T1D-AUTOANTIBODIES",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Testing and treating early stages of Type 1 diabetes",
    url: "https://www.niddk.nih.gov/health-information/professionals/diabetes-discoveries-practice/new-horizons-testing-diabetes",
    reviewedAt: "2026-09-13",
  },
  {
    id: "SRC-NIDDK-T1D-RISK",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    title: "Risk factors for Type 1 diabetes",
    url: "https://www.niddk.nih.gov/-/media/Files/Strategic-Plans/Diabetes-in-America-3rd-Edition/DIA_Ch11.pdf",
    reviewedAt: "2026-09-13",
  },
] as const;
