import type { InteractiveStory } from "@/features/stories/types/interactive-story";

export const devonNumberScreenStory: InteractiveStory = {
  id: "devon-number-screen",
  slug: "devon-number-screen",
  title: "The Number on the Screen",
  characterName: "Devon",
  disclosure:
    "About this story: Devon is a placeholder name. This is an original illustrative scenario inspired by concerns and reactions commonly reported by people monitoring Type 2 diabetes. It does not describe one specific individual and does not provide personalized instructions for responding to a glucose result.",
  topic: "A worrying reading",
  themes: [
    "glucose anxiety",
    "numbers as grades",
    "measurement context",
    "symptoms and care plans",
    "one result versus a pattern",
    "health team communication",
  ],
  learningObjective:
    "Separate a glucose result from self-judgment, consider symptoms and measurement context, follow an established care plan, and turn an isolated result into a useful question rather than an improvised treatment decision.",
  relatedLessonId: "20000000-0000-0000-0000-000000000008",
  relatedLessonLabel: "Lesson 8",
  relatedLessonTitle: "Lesson 8, Making Sense of Your Glucose",
  relatedLessonHref: "/lessons/8",
  estimatedMinutes: 8,
  estimatedTimeLabel: "7 to 9 minutes",
  medicalRiskLevel: "moderate",
  contentWarning:
    "This story includes an unexpected glucose result and a brief discussion of symptoms that may need urgent help.",
  reviewStatus: "not-reviewed",
  version: "1.0",
  sourceThemeNote:
    "Original composite narrative informed by common glucose-monitoring concerns. It avoids personal targets, treatment changes, and universal response thresholds.",
  visualTheme: "urgent-calm",
  emotionalArc: "uncertainty to context",
  dominantInteractionType: "reading-boundary",
  primaryAccent: "muted blue-green",
  closingTone: "grounded clarity",
  imagePath: "/stories/devon-number-screen-cover.webp",
  imagePrompt:
    "A cinematic editorial illustration of a thoughtful adult man sitting at a lived-in kitchen table at night, looking at an unbranded glucose meter with an unreadable display. A notebook, pen, water glass, and ordinary dinner remnants provide context. Warm cream and muted blue-green palette, restrained amber light, calm rather than alarming, no readable numbers, logos, labels, needles, or medical drama.",
  imageAlt:
    "An editorial illustration of a man sitting at a kitchen table at night while looking at a glucose meter with an unreadable display.",
  introduction:
    "Devon expected an ordinary evening. Then one unexpected glucose result made him question the meal he had eaten, the progress he thought he was making, and what might happen next.",
  whyItMatters:
    "This story explores how to respond to an unexpected reading without ignoring it, treating it as a personal failure, or making decisions before considering symptoms, context, and an established care plan.",
  scenes: [
    {
      id: "the-number",
      number: 1,
      title: "The Number",
      layout: "quiet-pause",
      tone: "tension",
      paragraphs: [
        "Devon checked his glucose later than usual that evening.",
        "Dinner had been ordinary. He had eaten with his family, cleared the table, and nearly forgotten to check at all.",
        "Then the number appeared.",
        "It was above the personal range his healthcare team had discussed with him.",
        "Devon stared at the screen longer than the test had taken.",
        "His first thought was not a question.",
        "It was a conclusion.",
        "I messed this up.",
        "His face felt warm. He looked back toward the kitchen table as though the result had identified a single mistake waiting there.",
        "The meter had given him one piece of information.",
        "Within seconds, Devon had turned it into a judgment about the entire day.",
      ],
      interactionType: "reading-boundary",
      interaction: {
        id: "devon-reading-boundary",
        purpose: "reading-boundary",
        engagement: "knowledge-application",
        prompt: "Where does the reading end—and the story around it begin?",
        instructions:
          "Place all six statements. The boundary separates information the screen can show from conclusions it cannot make.",
        options: [
          { id: "above-target", label: "The result is above Devon’s personal target." },
          { id: "worth-recording", label: "The result is worth recording." },
          { id: "needs-context", label: "The result needs context to interpret." },
          { id: "failed", label: "Devon failed." },
          { id: "permanent-change", label: "One dinner permanently changed his health." },
          { id: "exact-cause", label: "The number explains exactly why it happened." },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: true,
        learningPoint:
          "A meter reports a result. It cannot measure effort, explain an exact cause, or turn one moment into a verdict about a person.",
      },
      continueLabel: "See what the number became",
    },
    {
      id: "what-the-number-became",
      number: 2,
      title: "What the Number Became",
      layout: "thought-chain",
      tone: "tension",
      paragraphs: [
        "Devon carried the meter to the sofa.",
        "He tried to watch television, but the number remained in his mind.",
        "He replayed dinner.",
        "He remembered taking a second serving. Then he remembered the birthday cake someone had brought to work that afternoon.",
        "His thoughts moved quickly.",
        "Maybe I ruined the whole week.",
        "Maybe nothing I have been doing matters.",
        "Maybe this is what everything will look like now.",
        "The result had not changed.",
        "The story around it kept growing.",
      ],
      interactionType: "thought-chain",
      interaction: {
        id: "devon-thought-chain",
        purpose: "thought-chain",
        engagement: "knowledge-application",
        prompt: "Trace how one observation grew into a verdict.",
        instructions:
          "Build the four-part chain, then mark the last point still supported by direct evidence.",
        options: [
          { id: "observation", label: "The reading is above Devon’s personal range." },
          { id: "interpretation", label: "Dinner must have caused the result." },
          { id: "prediction", label: "Every future reading will look like this." },
          { id: "verdict", label: "Nothing Devon has done matters." },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: true,
        learningPoint:
          "The evidence boundary sits after the observation. Interpretation, prediction, and self-verdict may feel immediate without being established by one result.",
      },
      continueLabel: "Check what else may matter",
    },
    {
      id: "before-he-trusted-it",
      number: 3,
      title: "Before He Trusted It",
      layout: "process-path",
      tone: "pause",
      paragraphs: [
        "Devon reached toward the meter again.",
        "He wanted to test repeatedly until the screen showed something that felt less frightening.",
        "Then he noticed the plate he had carried from the table. A piece of cut fruit remained beside it.",
        "He could not remember whether he had washed and dried his hands before testing.",
        "That did not prove the reading was inaccurate.",
        "It gave him a reason to slow down and follow the instructions for the meter instead of chasing a different number.",
        "He opened the device guide.",
      ],
      interactionType: "measurement-context",
      interaction: {
        id: "devon-measurement-context",
        purpose: "measurement-context",
        engagement: "knowledge-application",
        prompt: "Build a calm measurement check.",
        instructions:
          "Choose the actions that add reliable context. Leave behind actions that chase reassurance or change treatment without a plan.",
        options: [
          { id: "notice-feeling", label: "Pause and notice how he feels." },
          { id: "follow-instructions", label: "Follow the meter instructions." },
          { id: "clean-hands", label: "Wash and dry his hands." },
          { id: "check-strip", label: "Confirm the strip and device are being used correctly." },
          { id: "record-context", label: "Record the result and useful context." },
          { id: "preferred-number", label: "Repeat until he gets a preferred number." },
          { id: "borrow-meter", label: "Borrow another meter without its instructions." },
          { id: "change-medicine", label: "Change medication before checking his care plan." },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: true,
        learningPoint:
          "Checking technique and following device instructions can improve measurement context without promising a different result or turning repeated testing into reassurance-seeking.",
      },
      paragraphsAfterInteraction: [
        "Devon followed the instructions and checked again as directed.",
        "The new result was different, but it was still above his personal range.",
        "Better technique gave him a more useful next question—not permission to ignore the result.",
      ],
      continueLabel: "Decide what matters now",
    },
    {
      id: "what-mattered-now",
      number: 4,
      title: "What Mattered Now",
      layout: "decision-focus",
      tone: "clarity",
      paragraphs: [
        "The second result did not answer every question.",
        "Devon wanted the meter to tell him what to do next, but the device could only show a number.",
        "He opened the written plan his healthcare team had given him.",
        "Before deciding what the result meant, he needed to consider something the screen could not show.",
        "How did he feel?",
        "Was this an isolated result or part of something repeating?",
        "What did his personal instructions say?",
        "Devon was alert. He was able to think clearly, breathe normally, and keep fluids down.",
        "He still felt worried.",
        "Worry mattered, but it was not the only information available.",
      ],
      interactionType: "urgency-context",
      interaction: {
        id: "devon-urgency-context",
        purpose: "urgency-context",
        engagement: "knowledge-application",
        prompt: "A number is only one part of the response.",
        instructions:
          "Open all three context areas, then match each example to the safest level of response.",
        options: [
          { id: "symptoms", label: "Symptoms: what is happening in the body right now?" },
          { id: "personal-plan", label: "Personal plan: what do the written instructions say?" },
          { id: "pattern", label: "Pattern: isolated, unusual, or repeating?" },
        ],
        feedbackMode: "choice-consequence",
        requiredForProgress: true,
        learningPoint:
          "Urgency depends on symptoms, the person’s established plan, and the broader pattern—not on a universal number supplied by a general story.",
      },
      continueLabel: "Prepare a useful message",
    },
    {
      id: "the-note-beside-the-meter",
      number: 5,
      title: "The Note Beside the Meter",
      layout: "communication-builder",
      tone: "clarity",
      paragraphs: [
        "Devon did not call three different relatives or search for the most frightening explanation.",
        "He placed a notebook beside the meter.",
        "He wanted to remember enough context to ask a useful question instead of beginning the conversation with:",
        "“My number was bad. What did I do wrong?”",
        "He wrote down the time.",
        "Then he paused.",
        "What else would help someone understand the result?",
      ],
      interactionType: "communication-builder",
      interaction: {
        id: "devon-communication-builder",
        purpose: "communication-builder",
        engagement: "knowledge-application",
        prompt: "Build a message that carries context instead of blame.",
        instructions:
          "Choose details that could help a qualified professional understand the situation. The finished note stays generic.",
        options: [
          { id: "result-time", label: "The result and the time it appeared" },
          { id: "meal-timing", label: "How the timing related to eating" },
          { id: "symptoms", label: "Symptoms or how he felt" },
          { id: "medicine-instructions", label: "Whether he followed medicine instructions" },
          { id: "routine-context", label: "Illness, stress, sleep, or a changed routine" },
          { id: "repeat-context", label: "Whether it was isolated or repeated as directed" },
          { id: "meter-steps", label: "Which meter instructions he followed" },
          { id: "food-promise", label: "A promise never to eat that meal again" },
          { id: "scary-search", label: "The most frightening complication he found online" },
          { id: "apology", label: "An apology for having the result" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: true,
        learningPoint:
          "A useful message names the result, timing, symptoms, relevant routine context, and the established instructions followed. It does not require an apology or a theory about blame.",
      },
      continueLabel: "See the longer view",
    },
    {
      id: "one-point-on-a-longer-line",
      number: 6,
      title: "One Point on a Longer Line",
      layout: "closing-wide",
      tone: "clarity",
      paragraphs: [
        "When Devon spoke with the healthcare team, no one asked him to defend the meal he had eaten.",
        "They reviewed the result, its timing, how he felt, and the instructions in his care plan.",
        "They also discussed what information would be useful if similar readings happened again.",
        "Devon did not receive a perfect explanation for one evening.",
        "He received something more practical.",
        "A way to notice, record, and ask.",
        "The number still mattered.",
        "It simply stopped standing alone.",
      ],
      interactionType: "pattern-comparison",
      interaction: {
        id: "devon-pattern-comparison",
        purpose: "pattern-comparison",
        engagement: "knowledge-application",
        prompt: "Which view makes a more useful care conversation possible?",
        instructions:
          "Compare one isolated point with several context-labeled moments. No values or extra testing schedule are added.",
        options: [
          { id: "isolated", label: "One isolated result" },
          { id: "contextual", label: "Several moments with relevant context" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: true,
        learningPoint:
          "A pattern with relevant context can support a better question than one isolated point. The care plan—not this story—determines when monitoring is useful.",
      },
      continueLabel: "Pause and Think",
    },
  ],
  predictionPrompt: "What most helped the number stop feeling like a verdict?",
  predictionChoices: [
    { id: "a", label: "Devon found a way to guarantee a preferred result." },
    { id: "b", label: "Devon decided the reading did not matter." },
    {
      id: "c",
      label: "Devon added symptoms, measurement context, his care plan, and a useful question.",
    },
    { id: "d", label: "Devon identified one meal as the permanent cause." },
  ],
  quiz: [
    {
      id: "devon-reading-meaning",
      prompt: "What can one glucose reading tell Devon by itself?",
      choices: [
        { id: "a", label: "Whether he tried hard enough that day." },
        { id: "b", label: "The exact food or event that caused it." },
        { id: "c", label: "The glucose result at that moment." },
        { id: "d", label: "What every future result will be." },
      ],
      correctChoiceId: "c",
      explanation:
        "A reading reports glucose at a moment. Context may make it more useful, but the meter cannot measure effort, prove one exact cause, or predict the future.",
      relatedSceneId: "the-number",
    },
    {
      id: "devon-unexpected-result",
      prompt: "What is the safest general response to an unexpected result?",
      choices: [
        { id: "a", label: "Change medication immediately." },
        { id: "b", label: "Keep retesting until the number feels reassuring." },
        {
          id: "c",
          label:
            "Consider symptoms, follow device instructions and the established care plan, and seek qualified help as directed.",
        },
        { id: "d", label: "Ignore it if the previous result was different." },
      ],
      correctChoiceId: "c",
      explanation:
        "Symptoms, measurement context, and the person’s established plan guide the response. Urgent symptoms should not wait for an app or repeated testing.",
      relatedSceneId: "what-mattered-now",
    },
    {
      id: "devon-useful-message",
      prompt: "Which message would give a healthcare professional the most useful context?",
      choices: [
        { id: "a", label: "“My number was bad. What did I do wrong?”" },
        { id: "b", label: "“I read about the worst possible complication online.”" },
        {
          id: "c",
          label:
            "“Here is the result, timing, how I felt, relevant context, and the instructions I followed.”",
        },
        { id: "d", label: "“I promise I will never eat that meal again.”" },
      ],
      correctChoiceId: "c",
      explanation:
        "A contextual note helps the care team interpret the moment without requiring Devon to invent a cause or apologize for the result.",
      relatedSceneId: "the-note-beside-the-meter",
    },
  ],
  resultIdeas: [
    "A glucose result is information, not a grade on effort.",
    "Symptoms, measurement context, and an established care plan shape the response.",
    "Context can turn an isolated result into a useful care-team question.",
  ],
  keyIdeaUnderstoodMessage:
    "You separated the information on the screen from the judgment and guesswork that can gather around it.",
  lessonEyebrow: "What changed",
  lessonHeading: "What Devon’s Experience Can Teach Us",
  interpretation: [
    "Devon’s first reaction treated one result as proof that he had failed. The screen had not said that. It had shown one piece of health information.",
    "Slowing down did not mean dismissing the result. It meant checking measurement context, noticing symptoms, and returning to instructions made for him.",
    "The healthcare conversation became more useful when Devon brought timing, symptoms, routine context, and the steps he had followed instead of an apology.",
    "One moment can matter without standing alone. Repeated context may reveal a useful pattern when monitoring is part of the care plan.",
  ],
  takeaway:
    "A worrying reading deserves attention without becoming a verdict. Notice symptoms, follow the device instructions and your established care plan, record useful context, and ask a qualified healthcare professional when the result or response is unclear.",
  privateReflectionPrompt:
    "When a health number feels frightening, what context could help you pause before turning it into a judgment?",
  completionHeading: "The number still mattered. It simply stopped standing alone.",
  completionMessage:
    "You followed Devon as he moved from self-blame toward measurement context, a personal safety plan, and a question his healthcare team could actually use.",
};
