import type { InteractiveStory } from "@/features/stories/types/interactive-story";

export const noraPrescriptionBagStory: InteractiveStory = {
  id: "nora-prescription-bag",
  slug: "nora-prescription-bag",
  title: "The Prescription Bag",
  characterName: "Nora",
  disclosure:
    "Nora is a placeholder name. This is an original illustrative scenario based on common questions people report when starting medication for Type 2 diabetes. It does not describe one specific individual or provide personal medication advice.",
  topic: "Starting medication",
  themes: [
    "medication stigma",
    "fear of failure",
    "prescription questions",
    "qualified information",
    "practical reminders",
    "support without judgment",
  ],
  learningObjective:
    "Show that medication can be one part of care, that prescription questions belong with a pharmacist or prescribing professional, and that a reminder must follow the directions provided.",
  relatedLessonId: "lesson-7",
  relatedLessonLabel: "Lesson 7",
  relatedLessonTitle: "Lesson 7, Medicines Are Tools, Not Judgments",
  relatedLessonHref: "/lessons/7",
  estimatedMinutes: 7,
  estimatedTimeLabel: "About 7 minutes",
  readerPartCount: 8,
  medicalRiskLevel: "moderate",
  reviewStatus: "not-reviewed",
  version: "2.1",
  sourceThemeNote:
    "Original composite narrative informed by common medication-stigma, uncertainty, and question-asking themes in diabetes education. It does not reproduce one person’s identity, wording, or treatment plan.",
  visualTheme: "hesitation",
  emotionalArc: "hesitation to a workable next step",
  dominantInteractionType: "question-building",
  primaryAccent: "pharmacy blue",
  closingTone: "ordinary and informed",
  imagePath: "/stories/nora-prescription-bag-cover.webp",
  imagePrompt:
    "A cinematic editorial scene in a quiet lived-in kitchen in early evening, with a thoughtful older woman seated at a table beside a closed unbranded pharmacy bag, reading glasses, and folded paper. Warm natural light, muted cream, green, and pharmacy blue tones. No loose pills, readable labels, logos, or medical drama.",
  imageAlt:
    "An editorial illustration of a woman sitting at a kitchen table while a closed pharmacy bag rests nearby.",
  introduction:
    "Nora brings home a new prescription but leaves it in the pharmacy bag while she tries to understand what it means.",
  whyItMatters:
    "Starting medication can bring practical questions and feelings about effort, identity, and judgment.",
  scenes: [
    {
      id: "the-pharmacy-bag",
      number: 1,
      title: "At the pharmacy",
      layout: "narrative-left",
      tone: "tension",
      paragraphs: [
        "Nora nodded while the pharmacist reviewed the label and written instructions. She put the bag on the passenger seat and drove home.",
        "She had always thought medication came after someone failed to make enough changes. Nobody at the appointment had said that. She still heard it when she looked at the bag.",
      ],
      interactionType: "belief-mapping",
      interaction: {
        id: "nora-belief-map",
        purpose: "belief-mapping",
        engagement: "optional-exploration",
        prompt: "What does the prescription say, and what meaning is Nora adding to it?",
        instructions: "Compare the label with Nora’s reaction.",
        options: [
          { id: "label", label: "A new prescription with specific directions" },
          { id: "judgment", label: "I did not try hard enough" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: false,
        learningPoint:
          "The prescription contains healthcare information. It does not grade Nora’s effort or character.",
      },
      continueLabel: "Go to the next morning",
    },
    {
      id: "still-on-the-counter",
      number: 2,
      title: "Still on the counter",
      layout: "decision-focus",
      tone: "tension",
      paragraphs: [
        "Nora saw the unopened bag while she made coffee. She was not forgetting it. She was waiting to feel certain.",
        "That evening she searched the medication name. One person felt better. Another described a side effect. Someone else said medication meant a person had not tried hard enough. Nora closed the browser with more questions than she started with.",
      ],
      interactionType: "source-pathway",
      interaction: {
        id: "nora-source-pathway",
        purpose: "source-evaluation",
        engagement: "optional-exploration",
        prompt: "Which sources can answer questions about Nora’s own prescription?",
        instructions: "Compare general experience with prescription-specific information.",
        options: [
          { id: "posts", label: "Other people’s online posts" },
          { id: "written", label: "The label and written pharmacy information" },
          { id: "professional", label: "A pharmacist or prescribing professional" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: false,
        learningPoint:
          "Other people’s experiences can feel relatable. A pharmacist, prescriber, label, and written information can address Nora’s specific prescription.",
      },
      continueLabel: "Continue to the weekend",
    },
    {
      id: "already",
      number: 3,
      title: "Her sister noticed",
      layout: "perspective-split",
      tone: "pause",
      paragraphs: [
        "Nora’s sister noticed the pharmacy bag during a visit and asked why medication was starting ‘already.’",
        "She may have meant concern. Nora heard blame. She folded the top of the bag closed and changed the subject.",
      ],
      interactionType: "perspective-switch",
      interaction: {
        id: "nora-perspective-response",
        purpose: "perspective-switch",
        secondaryPurpose: "rewrite-response",
        engagement: "knowledge-application",
        prompt: "What could her sister ask instead?",
        instructions: "Choose language that gives Nora control over how much she shares.",
        options: [
          { id: "a", label: "Are you sure you need it?" },
          { id: "b", label: "Maybe you should try harder first." },
          { id: "c", label: "How are you feeling about the new prescription?" },
        ],
        feedbackMode: "choice-consequence",
        requiredForProgress: false,
        learningPoint:
          "A supportive question can show concern without challenging Nora’s care or asking her to defend it.",
      },
      continueLabel: "Go to Monday’s call",
    },
    {
      id: "the-question-she-avoided",
      number: 4,
      title: "The pharmacy call",
      layout: "narrative-right",
      tone: "clarity",
      paragraphs: [
        "Nora called with a question about the directions. Before hanging up, she asked whether needing medication meant she had failed.",
        "The pharmacist said the prescription was based on her health needs, not a grade on her effort. Then they worked through the rest of her questions.",
      ],
      interactionType: "question-builder",
      interaction: {
        id: "nora-question-builder",
        purpose: "question-building",
        engagement: "optional-exploration",
        prompt: "Which questions would Nora want ready for the call?",
        instructions: "Save any useful questions.",
        options: [
          { id: "purpose", label: "What is this medication intended to help with?" },
          { id: "label", label: "How should I follow the directions on my label?" },
          { id: "concerns", label: "Which side effects or concerns should I discuss with you?" },
          { id: "uncertain", label: "What should I do if an instruction is unclear?" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: false,
        learningPoint:
          "Questions about changing or stopping medication belong with a pharmacist or prescribing professional.",
      },
      continueLabel: "See what Nora did next",
    },
    {
      id: "making-it-fit",
      number: 5,
      title: "A reminder that fits",
      layout: "stacked",
      tone: "clarity",
      paragraphs: [
        "After the call, Nora read the label and written instructions again. She decided to follow the directions she had been given.",
        "Now she needed a reminder that could fit into an ordinary day. It had to work with the prescription, not replace its instructions.",
      ],
      interactionType: "routine-anchor",
      interaction: {
        id: "nora-routine-anchor",
        purpose: "routine-planning",
        engagement: "meaningful-decision",
        prompt: "Which reminder could fit after Nora confirms the prescription directions?",
        instructions: "Choose one possible reminder.",
        options: [
          { id: "teeth", label: "Brushing her teeth" },
          { id: "coffee", label: "Making morning coffee" },
          { id: "alarm", label: "A phone reminder" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: false,
        learningPoint:
          "A routine can support memory only when it fits the label directions and guidance Nora received.",
      },
      continueLabel: "A few days later",
    },
    {
      id: "part-of-the-plan",
      number: 6,
      title: "Part of the plan",
      layout: "closing-wide",
      tone: "clarity",
      paragraphs: [
        "The pharmacy bag was gone from the counter. Nora still had questions, so she kept a note for her next appointment.",
        "Starting medication did not erase the meals, movement, rest, appointments, or support already in her life. It added another tool to the plan.",
      ],
      interactionType: "care-toolbox",
      interaction: {
        id: "nora-care-toolbox",
        purpose: "concept-integration",
        engagement: "optional-exploration",
        prompt: "What else can stay in Nora’s care plan?",
        instructions: "Compare the prescription with the full plan.",
        options: [
          { id: "medication", label: "Medication used as prescribed" },
          { id: "questions", label: "Questions for her care team" },
          { id: "daily-life", label: "Meals, movement, and rest that fit her life" },
          { id: "follow-up", label: "Appointments and support" },
        ],
        feedbackMode: "single-explanation",
        requiredForProgress: false,
        learningPoint:
          "Medication can be important without replacing the other parts of Nora’s care.",
      },
      continueLabel: "Finish story",
    },
  ],
  predictionPrompt: "What helped Nora move forward?",
  predictionChoices: [
    { id: "a", label: "Ignoring the prescription until she felt certain" },
    { id: "b", label: "Following advice from an anonymous post" },
    { id: "c", label: "Getting clear information and asking her questions" },
    { id: "d", label: "Treating medication as the only part of her care" },
  ],
  quiz: [
    {
      id: "nora-belief-question",
      prompt: "What made the prescription harder for Nora to open?",
      choices: [
        { id: "a", label: "The bag was difficult to open" },
        { id: "b", label: "She thought medication meant she had failed" },
        { id: "c", label: "The pharmacist refused to answer questions" },
        { id: "d", label: "She had lost the written information" },
      ],
      correctChoiceId: "b",
      explanation:
        "Nora had attached a judgment about effort to the prescription even though her healthcare team had not.",
      relatedSceneId: "the-pharmacy-bag",
    },
    {
      id: "nora-safest-response-question",
      prompt: "Who can clarify a question about a specific prescription?",
      choices: [
        { id: "a", label: "Anyone who uses a different medication" },
        { id: "b", label: "An anonymous post without medical context" },
        { id: "c", label: "A pharmacist or prescribing professional" },
        { id: "d", label: "A person who guesses from one glucose reading" },
      ],
      correctChoiceId: "c",
      explanation:
        "A pharmacist or prescribing professional can answer questions connected to the medication and care plan.",
      relatedSceneId: "still-on-the-counter",
    },
    {
      id: "nora-support-question",
      prompt: "Which response gives Nora room to decide what she shares?",
      choices: [
        { id: "a", label: "Are you sure you need it?" },
        { id: "b", label: "You should try harder first." },
        { id: "c", label: "How are you feeling about the prescription?" },
        { id: "d", label: "Do not tell anyone you are taking it." },
      ],
      correctChoiceId: "c",
      explanation: "This question shows concern without asking Nora to defend her care.",
      relatedSceneId: "already",
    },
  ],
  resultIdeas: [
    "Medication is not proof of failure.",
    "Prescription questions belong with qualified healthcare professionals.",
    "A reminder must fit the directions provided.",
  ],
  keyIdeaUnderstoodMessage:
    "Nora treated the prescription as part of her care, not a judgment about her effort.",
  lessonEyebrow: "What changed",
  lessonHeading: "Nora got answers and found a workable reminder.",
  interpretation: [
    "Nora had attached a judgment about effort to the prescription.",
    "The pharmacist answered the questions connected to her medication and directions.",
    "Medication became one part of her plan rather than a judgment about her character.",
  ],
  takeaway:
    "Medication can be part of care without being a judgment about effort. Prescription questions deserve answers from a qualified healthcare professional.",
  privateReflectionPrompt: "What question would help you understand a new prescription?",
  completionHeading: "Finished",
  completionMessage:
    "Nora got clear information, asked the question she had avoided, and found a reminder that followed her prescription directions.",
};
