import type { MythCheckCard } from "@/features/mythbusters/types/myth-check";

const card = (
  id: string,
  category: MythCheckCard["category"],
  claim: string,
  verdict: MythCheckCard["verdict"],
  explanation: string,
  takeaway: string,
  sourceIds: string[],
): MythCheckCard => ({
  id,
  category,
  claim,
  verdict,
  explanation,
  takeaway,
  sourceIds,
  status: "source-backed",
});

export const mythCheckCards: readonly MythCheckCard[] = [
  card("MYTH-BASICS-01", "basics", "Eating sugar is the only reason people develop Type 2 diabetes.", "myth", "Type 2 diabetes develops through a combination of insulin resistance, changes in insulin production, genetics, age, family history, environment, activity, body weight, and other factors. Sugary drinks are associated with increased risk, but sugar is not the single cause.", "Type 2 diabetes has multiple causes and is not a simple result of one food or one choice.", ["ADA_MYTHS", "CDC_TYPE2"]),
  card("MYTH-BASICS-02", "basics", "Only people with overweight develop Type 2 diabetes.", "myth", "Body weight is one risk factor, but it is not the only one. People at many body sizes can develop Type 2 diabetes.", "A person’s appearance cannot tell you whether they have or may develop diabetes.", ["ADA_MYTHS", "CDC_TYPE2"]),
  card("MYTH-BASICS-03", "basics", "Type 2 diabetes can affect children, teenagers, and younger adults.", "fact", "Type 2 diabetes is more common in middle-aged and older adults, but it is increasingly diagnosed in children, teenagers, and younger adults.", "Type 2 diabetes is not limited to one age group.", ["CDC_TYPE2", "ADA_TYPE2"]),
  card("MYTH-BASICS-04", "basics", "Diabetes can be caught from another person.", "myth", "Diabetes is not contagious. It cannot spread between people like a cold or the flu.", "You cannot catch diabetes from someone else.", ["ADA_MYTHS"]),
  card("MYTH-BASICS-05", "basics", "A person can have Type 2 diabetes without noticing clear symptoms.", "fact", "Type 2 diabetes symptoms can develop slowly, be mild, or go unnoticed. Some people do not notice symptoms at all.", "Feeling fine does not replace appropriate testing and follow-up.", ["CDC_TYPE2", "CDC_TESTING"]),
  card("MYTH-BASICS-06", "basics", "Prediabetes always develops into Type 2 diabetes.", "myth", "Prediabetes increases the risk of Type 2 diabetes, but progression is not guaranteed. Proven lifestyle changes can prevent or delay Type 2 diabetes for many people.", "Prediabetes is serious, but early action can make a difference.", ["CDC_PREDIABETES"]),
  card("MYTH-BASICS-07", "basics", "Losing weight will put every person with Type 2 diabetes into remission.", "depends", "Significant weight loss may lead to remission for some people, but it does not happen for everyone and is not guaranteed. Individual biology, diabetes duration, treatment, and other factors matter.", "Remission is possible for some people, but no single result is guaranteed.", ["NIDDK_REMISSION"]),
  card("MYTH-BASICS-08", "basics", "Type 2 diabetes is caused only by a person making bad choices.", "myth", "Type 2 diabetes is influenced by many biological, genetic, environmental, social, and behavioral factors. Describing it as a personal failure is inaccurate and creates stigma.", "Diabetes deserves practical support, not blame.", ["ADA_MYTHS", "CDC_TYPE2"]),
  card("MYTH-BASICS-09", "basics", "Type 2 diabetes remission means the condition has been permanently cured.", "myth", "Remission means glucose levels remain below the diabetes range without glucose-lowering medicine for a defined period. Health professionals use the word remission rather than cure because diabetes can return and continued follow-up remains important.", "Remission is not the same as a permanent cure.", ["NIDDK_REMISSION"]),

  card("MYTH-FOOD-01", "food", "People with diabetes must avoid all carbohydrates.", "myth", "Carbohydrates can be part of an eating plan for diabetes. The type, amount, portion, and combination with other foods can affect blood glucose.", "Carbohydrates are managed, not automatically forbidden.", ["ADA_CARBS", "CDC_CARBS"]),
  card("MYTH-FOOD-02", "food", "Fruit can fit into an eating plan for diabetes.", "fact", "Fruit contains carbohydrate, but it also provides vitamins, minerals, and often fiber. Fresh, frozen, and canned fruit without added sugars can fit into diabetes meal planning.", "Fruit is not automatically off-limits because it contains natural sugar.", ["ADA_FRUIT", "ADA_EATING"]),
  card("MYTH-FOOD-03", "food", "People with diabetes need special foods labeled for diabetes.", "myth", "People with diabetes generally do not need separate or specially marketed foods. Many of the same balanced eating principles used for overall health also apply to diabetes.", "A diabetes label does not automatically make a food necessary or better.", ["ADA_MYTHS"]),
  card("MYTH-FOOD-04", "food", "Sweets can sometimes fit into an eating plan for diabetes.", "depends", "Sweets are not universally forbidden, but their amount, frequency, total carbohydrates, and place within an individual eating and treatment plan matter.", "The answer is usually about context and amount, not a permanent ban.", ["ADA_MYTHS"]),
  card("MYTH-FOOD-05", "food", "A food labeled sugar-free is always carbohydrate-free.", "myth", "Sugar-free foods can still contain starches, sugar alcohols, or other carbohydrates. The total-carbohydrate line provides more useful information than the front label alone.", "Sugar-free and carbohydrate-free do not mean the same thing.", ["ADA_CARB_TYPES"]),
  card("MYTH-FOOD-06", "food", "Net carbs is an official FDA-defined measurement.", "myth", "Net carbs does not have a standard legal definition recognized by the FDA. Different products may calculate it differently.", "Check total carbohydrate rather than relying only on a net-carbs claim.", ["ADA_CARB_TYPES"]),
  card("MYTH-FOOD-07", "food", "A low-carbohydrate eating pattern is the best choice for every person with diabetes.", "depends", "A lower-carbohydrate approach may work for some people, but there is no single eating pattern that is best for everyone. Preferences, health needs, medicines, culture, access, and goals differ.", "Diabetes eating plans should not be one-size-fits-all.", ["ADA_CARBS", "ADA_MYTHS"]),
  card("MYTH-FOOD-08", "food", "The type and amount of carbohydrate can affect blood glucose.", "fact", "Carbohydrates are broken down into glucose. Different foods, portions, fiber content, and meal combinations can affect how quickly and how much blood glucose changes.", "Carbohydrates matter, but their effects are more complex than simply good or bad.", ["ADA_CARBS", "CDC_CARBS"]),

  card("MYTH-MONITORING-01", "monitoring", "An A1C result shows every daily high and low blood glucose episode.", "myth", "A1C estimates average blood glucose over roughly the previous three months. It does not show every sudden high, low, or daily pattern.", "An average can hide important variation.", ["NIDDK_A1C", "CDC_A1C"]),
  card("MYTH-MONITORING-02", "monitoring", "An A1C result and a current glucose reading provide the same information.", "myth", "A glucose reading shows glucose at a particular moment. A1C estimates an average over a much longer period.", "Current readings and A1C answer different questions.", ["NIDDK_A1C", "ADA_A1C"]),
  card("MYTH-MONITORING-03", "monitoring", "You can always tell what your blood glucose is doing by how you feel.", "myth", "High or low blood glucose may not always cause symptoms a person notices. Symptoms can also have many causes, so feelings alone do not provide a glucose measurement.", "Use the monitoring approach recommended for you rather than relying only on symptoms.", ["CDC_TYPE2", "ADA_CHECKS"]),
  card("MYTH-MONITORING-04", "monitoring", "Every person with Type 2 diabetes needs to check blood glucose at home every day.", "depends", "Monitoring needs differ based on medicines, risk of low glucose, treatment changes, illness, goals, and the person’s care plan. Some people need frequent checks while others may not.", "Monitoring frequency should match the individual treatment plan.", ["ADA_CHECKS", "CDC_MONITORING"]),
  card("MYTH-MONITORING-05", "monitoring", "An online risk test can diagnose prediabetes.", "myth", "A risk test can identify factors associated with higher risk, but it cannot diagnose prediabetes. Diagnosis requires an appropriate blood test interpreted by a health professional.", "Risk screening and diagnosis are not the same thing.", ["CDC_RISK_TEST", "CDC_TESTING"]),
  card("MYTH-MONITORING-06", "monitoring", "Type 2 diabetes can be diagnosed from symptoms alone.", "myth", "Symptoms may lead someone to seek testing, but blood testing is used to diagnose diabetes. Some people have few or no noticeable symptoms.", "Symptoms can raise a question, but testing establishes the diagnosis.", ["CDC_TESTING", "NIDDK_TESTING"]),
  card("MYTH-MONITORING-07", "monitoring", "A1C and home or continuous glucose readings can provide different useful information.", "fact", "A1C provides a longer-term average, while a meter or continuous glucose monitor can show current readings, daily patterns, and variation that an average may hide.", "Different monitoring tools provide different views of glucose.", ["NIDDK_A1C", "ADA_A1C", "ADA_CHECKS"]),

  card("MYTH-TREATMENT-01", "treatment", "Starting insulin means a person failed to manage Type 2 diabetes.", "myth", "Type 2 diabetes can change over time as the body produces less insulin or uses it less effectively. Insulin is one treatment tool, not evidence of failure.", "Treatment changes reflect changing health needs, not personal worth.", ["ADA_MYTHS", "ADA_TYPE2"]),
  card("MYTH-TREATMENT-02", "treatment", "Everyone with Type 2 diabetes should receive the same treatment.", "myth", "Treatment can include eating-pattern changes, physical activity, oral medicines, injectable medicines, insulin, education, and other support. The combination differs from person to person.", "Diabetes treatment is individualized.", ["ADA_TYPE2"]),
  card("MYTH-TREATMENT-03", "treatment", "Lifestyle changes mean medicine is never needed.", "myth", "Food, movement, sleep, and other habits can be important, but some people also need medicine to manage diabetes. Needing medicine is not a failure.", "Lifestyle support and medicine can work together.", ["ADA_TYPE2"]),
  card("MYTH-TREATMENT-04", "treatment", "Taking diabetes medicine makes food, movement, and other self-care unimportant.", "myth", "Medicines are one part of diabetes care. Eating patterns, movement, education, monitoring when appropriate, follow-up, and emotional support may still matter.", "Medicine does not replace the rest of diabetes care.", ["ADA_TYPE2", "NIDDK_MANAGEMENT"]),
  card("MYTH-TREATMENT-05", "treatment", "A diabetes product described as natural or herbal is automatically safe and effective.", "myth", "Natural claims do not prove safety or effectiveness. The FDA has warned that some unapproved diabetes products contain hidden ingredients or may delay effective treatment.", "Natural is a marketing description, not proof of safety.", ["FDA_DIABETES_SCAMS", "FDA_HEALTH_FRAUD"]),
  card("MYTH-TREATMENT-06", "treatment", "A product promising a fast diabetes cure is trustworthy when it has convincing testimonials.", "myth", "Testimonials are not scientific evidence and can be misleading or fabricated. Quick-cure claims are a warning sign for health fraud.", "Extraordinary treatment claims require reliable evidence, not testimonials.", ["FDA_HEALTH_FRAUD", "FDA_SCAM_SIGNS"]),
  card("MYTH-TREATMENT-07", "treatment", "Diabetes complications are inevitable.", "myth", "Diabetes raises the risk of several health problems, but complications are not guaranteed. Ongoing management, screening, preventive care, and treatment can reduce risk or identify problems earlier.", "Higher risk does not mean an outcome is unavoidable.", ["ADA_MYTHS", "CDC_TYPE2"]),
  card("MYTH-TREATMENT-08", "treatment", "Regular diabetes care can help reduce the risk of complications.", "fact", "Managing blood glucose and other health factors, attending follow-up care, and completing recommended screenings can help prevent, delay, or identify diabetes-related problems.", "Consistent care can meaningfully lower risk.", ["ADA_MYTHS", "CDC_TYPE2", "NIDDK_MANAGEMENT"]),
];
