export const type2DiabetesResources = [
  {
    id: "type-2-diabetes-basics",
    title: "Type 2 diabetes basics",
    organization: "Centers for Disease Control and Prevention",
    category: "Start here",
    description:
      "A clear overview of what Type 2 diabetes is, how it affects blood glucose, and how it is managed.",
    editorial_label: "Recommended",
    format: "Explainer",
    reading_level: "Beginner",
    reading_minutes: 4,
    url: "https://www.cdc.gov/diabetes/about/about-type-2-diabetes.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "understanding-a1c",
    title: "What A1C sees and what it misses",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Start here",
    description:
      "This guide explains what an A1C result measures, what can affect it, and why targets vary by person.",
    editorial_label: "Editor's pick",
    format: "Explainer",
    reading_level: "Beginner",
    reading_minutes: 6,
    url: "https://www.niddk.nih.gov/health-information/diagnostic-tests/a1c-test",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "monitoring-blood-sugar",
    title: "When a glucose reading needs context",
    organization: "Centers for Disease Control and Prevention",
    category: "Start here",
    description:
      "Food, sleep, stress, activity and timing can help explain an individual glucose reading.",
    editorial_label: "Quick guide",
    format: "Guide",
    reading_level: "Everyday",
    reading_minutes: 5,
    url: "https://www.cdc.gov/diabetes/diabetes-testing/monitoring-blood-sugar.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "diabetes-meal-planning",
    title: "Plan a balanced plate",
    organization: "Centers for Disease Control and Prevention",
    category: "Everyday habits",
    description:
      "Use a simple plate framework to plan portions while keeping familiar foods in the meal.",
    editorial_label: "Editor's pick",
    format: "Guide",
    reading_level: "Beginner",
    reading_minutes: 7,
    url: "https://www.cdc.gov/diabetes/healthy-eating/diabetes-meal-planning.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "cultural-foods",
    title: "Include familiar and cultural foods",
    organization: "Centers for Disease Control and Prevention",
    category: "Everyday habits",
    description:
      "Rice, tortillas, noodles, bread and celebration dishes can fit into a balanced eating plan.",
    editorial_label: "Recommended",
    format: "Guide",
    reading_level: "Everyday",
    reading_minutes: 5,
    url: "https://www.cdc.gov/diabetes/healthy-eating/diabetes-cultural-foods.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "physical-activity",
    title: "Why ten active minutes can matter",
    organization: "Centers for Disease Control and Prevention",
    category: "Everyday habits",
    description:
      "A short walk, chair movement, or another brief activity can support glucose management and general health.",
    editorial_label: "Editor's pick",
    format: "Guide",
    reading_level: "Beginner",
    reading_minutes: 5,
    url: "https://www.cdc.gov/diabetes/living-with/physical-activity.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "diabetes-treatments",
    title: "How diabetes treatments are chosen",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Treatment & safety",
    description:
      "See why one person may use metformin while another uses insulin or a different medicine.",
    editorial_label: "Evidence-based",
    format: "Explainer",
    reading_level: "Deeper read",
    reading_minutes: 8,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/insulin-medicines-treatments",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "low-blood-sugar",
    title: "Know the signs of a low",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Treatment & safety",
    description:
      "Shaky, sweaty, suddenly confused: a low can arrive quickly. Know the signals and the plan before you need either.",
    editorial_label: "Care essential",
    format: "Checklist",
    reading_level: "Everyday",
    reading_minutes: 6,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/low-blood-glucose-hypoglycemia",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "managing-sick-days",
    title: "When illness changes the rules",
    organization: "Centers for Disease Control and Prevention",
    category: "Treatment & safety",
    description:
      "Illness can change glucose and medication needs, even when you eat less. A written sick-day plan explains what to do.",
    editorial_label: "Care essential",
    format: "Checklist",
    reading_level: "Everyday",
    reading_minutes: 5,
    url: "https://www.cdc.gov/diabetes/living-with/managing-sick-days.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "heart-disease-and-stroke",
    title: "The diabetes–heart connection",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Whole-body health",
    description:
      "Blood pressure, cholesterol, smoking and glucose can all affect cardiovascular risk.",
    editorial_label: "Recommended",
    format: "Guide",
    reading_level: "Deeper read",
    reading_minutes: 7,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/heart-disease-stroke",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "kidney-health",
    title: "Protecting your kidneys",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Whole-body health",
    description:
      "Early kidney changes may cause no symptoms. Blood and urine tests can find them sooner.",
    editorial_label: "Evidence-based",
    format: "Guide",
    reading_level: "Deeper read",
    reading_minutes: 7,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/diabetic-kidney-disease",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "eye-health",
    title: "Clear vision can hide early changes",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Whole-body health",
    description:
      "Clear vision does not always mean the retina is unchanged. A diabetes eye exam looks beyond what you can notice yourself.",
    editorial_label: "Care essential",
    format: "Guide",
    reading_level: "Everyday",
    reading_minutes: 6,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/diabetic-eye-disease",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "foot-care",
    title: "The two-minute foot check",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Whole-body health",
    description:
      "Reduced feeling or circulation can make a small sore more serious. A daily check helps find problems early.",
    editorial_label: "Quick guide",
    format: "Checklist",
    reading_level: "Beginner",
    reading_minutes: 5,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/foot-problems",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "oral-health",
    title: "What your gums can tell you",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Whole-body health",
    description:
      "Gums and blood glucose can influence each other. Here is what to watch for and what your dentist needs to know.",
    editorial_label: "Recommended",
    format: "Guide",
    reading_level: "Everyday",
    reading_minutes: 6,
    url: "https://www.niddk.nih.gov/health-information/diabetes/overview/preventing-problems/gum-disease-dental-problems",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "diabetes-and-mental-health",
    title: "When diabetes care feels heavy",
    organization: "Centers for Disease Control and Prevention",
    category: "Support & access",
    description:
      "When diabetes is always in the background, care can start to feel heavy. Distress is common, real, and worth talking about.",
    editorial_label: "Recommended",
    format: "Guide",
    reading_level: "Everyday",
    reading_minutes: 6,
    url: "https://www.cdc.gov/diabetes/living-with/mental-health.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "diabetes-education-and-support",
    title: "Diabetes education and support",
    organization: "Centers for Disease Control and Prevention",
    category: "Support & access",
    description:
      "Diabetes education specialists help people apply care instructions to meals, medicines and daily routines.",
    editorial_label: "Recommended",
    format: "Guide",
    reading_level: "Beginner",
    reading_minutes: 5,
    url: "https://www.cdc.gov/diabetes/education-support-programs/index.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "financial-help",
    title: "When the cost of care becomes a barrier",
    organization: "National Institute of Diabetes and Digestive and Kidney Diseases",
    category: "Support & access",
    description:
      "Medicines, supplies, visits, insurance: the costs add up fast. Start here when paying for care becomes part of the problem.",
    editorial_label: "Worth keeping",
    format: "Guide",
    reading_level: "Everyday",
    reading_minutes: 8,
    url: "https://www.niddk.nih.gov/health-information/diabetes/financial-help-diabetes-care",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
  {
    id: "emergency-preparedness",
    title: "Build a diabetes emergency kit",
    organization: "Centers for Disease Control and Prevention",
    category: "Support & access",
    description:
      "A power outage changes more than the lights when medicine, refrigeration, and supplies are involved. Build the kit before the forecast turns.",
    editorial_label: "Worth keeping",
    format: "Checklist",
    reading_level: "Beginner",
    reading_minutes: 5,
    url: "https://www.cdc.gov/diabetes/articles/diabetes-care-emergencies.html",
    verified_at: "2026-07-21",
    status: "reviewed",
  },
] as const;
