import type {
  MilestoneCategory,
  MilestoneDefinition,
  MilestonePathway,
} from "@/features/achievements/types/milestone";

const define = (
  id: string,
  slug: string,
  name: string,
  shortDescription: string,
  description: string,
  category: MilestoneCategory,
  icon: MilestoneDefinition["icon"],
  criteriaLabel: string,
  order: number,
): MilestoneDefinition => ({
  id,
  slug,
  name,
  shortDescription,
  description,
  category,
  icon,
  criteriaLabel,
  order,
  hidden: false,
});

export const milestoneDefinitions = [
  define(
    "MILESTONE-FIRST-STEP",
    "first-step",
    "First Step",
    "Every journey starts somewhere.",
    "You completed your first Health Decoded lesson.",
    "learning",
    "first-step",
    "Complete one Health Decoded lesson.",
    1,
  ),
  define(
    "MILESTONE-BUILDING-RHYTHM",
    "building-rhythm",
    "Building a Rhythm",
    "Learning is becoming part of your rhythm.",
    "You returned to learn and completed three different lessons.",
    "learning",
    "building-rhythm",
    "Complete three distinct lessons.",
    2,
  ),
  define(
    "MILESTONE-WEEK-OF-LEARNING",
    "week-of-learning",
    "A Week of Learning",
    "Seven lessons, each one building your confidence.",
    "You completed seven different lessons in the Foundation journey.",
    "learning",
    "week-of-learning",
    "Complete seven distinct lessons.",
    3,
  ),
  define(
    "MILESTONE-LEARNING-IN-MOTION",
    "learning-in-motion",
    "Learning in Motion",
    "Your knowledge keeps moving forward.",
    "You completed 10 different Health Decoded lessons.",
    "learning",
    "learning-motion",
    "Complete 10 distinct lessons.",
    4,
  ),
  define(
    "MILESTONE-FOUNDATION-COMPLETE",
    "foundation-complete",
    "Foundation Complete",
    "A strong foundation for what comes next.",
    "You completed the foundational section of your Health Decoded journey.",
    "learning",
    "foundation",
    "Complete all 14 lessons in the Foundation phase.",
    5,
  ),
  define(
    "MILESTONE-THOUGHTFUL-REFLECTION",
    "thoughtful-reflection",
    "Thoughtful Reflection",
    "You made space to connect learning with life.",
    "You paused to connect three lessons with your own experience.",
    "learning",
    "reflection",
    "Save a reflection in three different lessons.",
    6,
  ),
  define(
    "MILESTONE-MYTH-CHECKER",
    "myth-checker",
    "Myth Checker",
    "You looked beyond the claim.",
    "You completed a full Diabetes Myth Check round.",
    "understanding",
    "myth-checker",
    "Complete one full Myth Check round.",
    7,
  ),
  define(
    "MILESTONE-SECOND-LOOK",
    "second-look",
    "Second Look",
    "Curiosity is worth another look.",
    "You revisited claims that deserved another look.",
    "understanding",
    "second-look",
    "Complete a replay round of claims you wanted to revisit.",
    8,
  ),
  define(
    "MILESTONE-EVIDENCE-SEEKER",
    "evidence-seeker",
    "Evidence Seeker",
    "You followed the evidence to its source.",
    "You checked the evidence behind three different diabetes claims.",
    "understanding",
    "evidence",
    "Open sources for three distinct claims in one session.",
    9,
  ),
  define(
    "MILESTONE-PRIORITIES-SET",
    "priorities-set",
    "Priorities Set",
    "You named what matters most.",
    "You identified the most important things you want to discuss.",
    "appointment",
    "priorities",
    "Create three top priorities in Appointment Preparation.",
    10,
  ),
  define(
    "MILESTONE-QUESTIONS-READY",
    "questions-ready",
    "Questions Ready",
    "A thoughtful question can open the conversation.",
    "You prepared questions for your health professional.",
    "appointment",
    "questions",
    "Create three questions across at least two categories.",
    11,
  ),
  define(
    "MILESTONE-APPOINTMENT-READY",
    "appointment-ready",
    "Appointment Ready",
    "You prepared for a more useful conversation.",
    "You created a complete preparation summary for an upcoming conversation with a health professional.",
    "appointment",
    "appointment",
    "Add meaningful content to four of the five preparation areas.",
    12,
  ),
  define(
    "MILESTONE-PLAN-IN-HAND",
    "plan-in-hand",
    "Plan in Hand",
    "Your preparation is ready to come with you.",
    "You created a copy of your appointment preparation to use when you need it.",
    "appointment",
    "plan",
    "Print or copy a nonempty preparation summary.",
    13,
  ),
  define(
    "MILESTONE-CONVERSATION-BUILDER",
    "conversation-builder",
    "Conversation Builder",
    "Support starts with how we listen and speak.",
    "You practiced ways to make diabetes conversations more supportive.",
    "support",
    "conversation",
    "In Caregiver Module 1, reach the central idea, finish the Observation Workbench, and view the practical takeaway.",
    14,
  ),
  define(
    "MILESTONE-SUPPORT-WITH-PERMISSION",
    "support-with-permission",
    "Support With Permission",
    "Care and respect can share the same space.",
    "You learned how to support someone while respecting their choices and boundaries.",
    "support",
    "permission",
    "In Caregiver Module 2, reach the central idea, finish the permission-based offer, and view the practical takeaway.",
    15,
  ),
  define(
    "MILESTONE-EVERYDAY-ALLY",
    "everyday-ally",
    "Everyday Ally",
    "Small acts of support can matter deeply.",
    "You practiced offering help that fits the person and the moment.",
    "support",
    "everyday-support",
    "In Caregiver Module 3, reach the central idea, finish Request Matching, and view the practical takeaway.",
    16,
  ),
  define(
    "MILESTONE-STEADY-SUPPORT",
    "steady-support",
    "Steady Support",
    "Calm support can help in uncertain moments.",
    "You practiced responding calmly when something feels wrong.",
    "support",
    "steady-support",
    "In Caregiver Module 4, reach the central idea, finish Source Matching, and view the practical takeaway.",
    17,
  ),
  define(
    "MILESTONE-SUSTAINABLE-SUPPORT",
    "sustainable-support",
    "Sustainable Support",
    "Support lasts longer when everyone is cared for.",
    "You explored boundaries and shared responsibility that can make support last.",
    "support",
    "sustainable-support",
    "In Caregiver Module 5, reach the central idea, finish the Responsibility Map, and view the practical takeaway.",
    18,
  ),
  define(
    "MILESTONE-FOUND-TRUSTED-SUPPORT",
    "found-trusted-support",
    "Found Trusted Support",
    "Reliable help is easier to find when you know where to look.",
    "You explored a trusted diabetes education or support option.",
    "resources",
    "trusted-support",
    "Open the verified diabetes education and support guide.",
    19,
  ),
  define(
    "MILESTONE-PERSONAL-TOOLKIT",
    "personal-toolkit",
    "Personal Toolkit",
    "You are building a toolkit that fits your life.",
    "You used several Health Decoded tools to learn, prepare, and find support.",
    "toolkit",
    "toolkit",
    "Earn milestones in four different learning and support categories.",
    20,
  ),
  define(
    "MILESTONE-IN-YOUR-OWN-WORDS",
    "in-your-own-words",
    "In Your Own Words",
    "You made a health idea your own.",
    "You clearly explained a Health Decoded concept in language that felt natural to you.",
    "understanding",
    "in-your-own-words",
    "Earn a “Got it” result in Explain It Back.",
    21,
  ),
  define(
    "MILESTONE-MEMORY-IN-MOTION",
    "memory-in-motion",
    "Memory in Motion",
    "You returned to strengthen what you learned.",
    "You completed a Quick Review for a concept you had already explored.",
    "learning",
    "memory-in-motion",
    "Complete one available Quick Review.",
    22,
  ),
  define(
    "MILESTONE-LABEL-WISE",
    "label-wise",
    "Label Wise",
    "You looked at the whole label with context.",
    "You completed the food-label exercise and practiced finding useful places to begin.",
    "understanding",
    "label-wise",
    "Answer every question in Decode the Label and reach the recap.",
    23,
  ),
  define(
    "MILESTONE-STORY-EXPLORER",
    "story-explorer",
    "Story Explorer",
    "You followed a lived experience all the way through.",
    "You completed an interactive story and connected its ideas with everyday life.",
    "learning",
    "story-explorer",
    "Reach the ending of one interactive story.",
    24,
  ),
  define(
    "MILESTONE-CONCEPTS-MADE-CLEAR",
    "concepts-made-clear",
    "Concepts Made Clear",
    "Clarity grows each time you put an idea into your own words.",
    "You clearly explained three different Health Decoded concepts in language that felt natural to you.",
    "understanding",
    "concepts-made-clear",
    "Earn a “Got it” result for three distinct Explain It Back concepts.",
    25,
  ),
  define(
    "MILESTONE-MANY-PERSPECTIVES",
    "many-perspectives",
    "Many Perspectives",
    "Every story adds another way of seeing.",
    "You completed every interactive story and explored four different lived experiences.",
    "learning",
    "many-perspectives",
    "Reach the ending of all four interactive stories.",
    26,
  ),
  define(
    "MILESTONE-CIRCLE-OF-SUPPORT",
    "circle-of-support",
    "Circle of Support",
    "Thoughtful support makes room for both people.",
    "You completed the full caregiver learning collection, from listening well to making support sustainable.",
    "support",
    "circle-of-support",
    "Complete all five Caregiver Pathway modules.",
    27,
  ),
  define(
    "MILESTONE-RESOURCE-NAVIGATOR",
    "resource-navigator",
    "Resource Navigator",
    "You know how to follow a question toward trusted guidance.",
    "You explored three different reviewed resources from trusted health organizations.",
    "resources",
    "resource-navigator",
    "Open three distinct guides in Trusted Resources.",
    28,
  ),
] as const satisfies readonly MilestoneDefinition[];

export const milestoneDefinitionById = new Map(
  milestoneDefinitions.map((definition) => [definition.id, definition]),
);

export const milestonePathwayById = new Map<string, MilestonePathway>([
  [
    "MILESTONE-FIRST-STEP",
    { href: "/journey", actionLabel: "Continue your journey", target: 1, unit: "lesson completed" },
  ],
  [
    "MILESTONE-BUILDING-RHYTHM",
    {
      href: "/journey",
      actionLabel: "Continue your journey",
      target: 3,
      unit: "lessons completed",
    },
  ],
  [
    "MILESTONE-WEEK-OF-LEARNING",
    {
      href: "/journey",
      actionLabel: "Continue your journey",
      target: 7,
      unit: "lessons completed",
    },
  ],
  [
    "MILESTONE-LEARNING-IN-MOTION",
    {
      href: "/journey",
      actionLabel: "Continue your journey",
      target: 10,
      unit: "lessons completed",
    },
  ],
  [
    "MILESTONE-FOUNDATION-COMPLETE",
    {
      href: "/journey",
      actionLabel: "Continue your journey",
      target: 14,
      unit: "Foundation lessons completed",
    },
  ],
  [
    "MILESTONE-THOUGHTFUL-REFLECTION",
    {
      href: "/journey",
      actionLabel: "Open your journey",
      target: 3,
      unit: "lesson reflections saved",
    },
  ],
  [
    "MILESTONE-MYTH-CHECKER",
    {
      href: "/myth-check",
      actionLabel: "Start a Myth Check round",
      target: 1,
      unit: "round completed",
    },
  ],
  [
    "MILESTONE-SECOND-LOOK",
    {
      href: "/myth-check",
      actionLabel: "Revisit a Myth Check round",
      target: 1,
      unit: "replay round completed",
    },
  ],
  [
    "MILESTONE-EVIDENCE-SEEKER",
    {
      href: "/myth-check",
      actionLabel: "Review claim sources",
      target: 3,
      unit: "claim sources reviewed in one session",
    },
  ],
  [
    "MILESTONE-PRIORITIES-SET",
    {
      href: "/appointment-prep",
      actionLabel: "Prepare your priorities",
      target: 3,
      unit: "priorities prepared",
    },
  ],
  [
    "MILESTONE-QUESTIONS-READY",
    {
      href: "/appointment-prep",
      actionLabel: "Prepare your questions",
      target: 3,
      unit: "questions prepared across two categories",
    },
  ],
  [
    "MILESTONE-APPOINTMENT-READY",
    {
      href: "/appointment-prep",
      actionLabel: "Build your appointment summary",
      target: 4,
      unit: "preparation areas completed",
    },
  ],
  [
    "MILESTONE-PLAN-IN-HAND",
    {
      href: "/appointment-prep",
      actionLabel: "Create a plan to take with you",
      target: 1,
      unit: "summary copied or printed",
    },
  ],
  [
    "MILESTONE-CONVERSATION-BUILDER",
    {
      href: "/caregiver/modules/what-they-may-be-feeling",
      actionLabel: "Start Caregiver Module 1",
      target: 3,
      unit: "module steps completed",
    },
  ],
  [
    "MILESTONE-SUPPORT-WITH-PERMISSION",
    {
      href: "/caregiver/modules/support-without-taking-over",
      actionLabel: "Start Caregiver Module 2",
      target: 3,
      unit: "module steps completed",
    },
  ],
  [
    "MILESTONE-EVERYDAY-ALLY",
    {
      href: "/caregiver/modules/everyday-support-that-actually-helps",
      actionLabel: "Start Caregiver Module 3",
      target: 3,
      unit: "module steps completed",
    },
  ],
  [
    "MILESTONE-STEADY-SUPPORT",
    {
      href: "/caregiver/modules/when-something-feels-wrong",
      actionLabel: "Start Caregiver Module 4",
      target: 3,
      unit: "module steps completed",
    },
  ],
  [
    "MILESTONE-SUSTAINABLE-SUPPORT",
    {
      href: "/caregiver/modules/the-caregiver-matters-too",
      actionLabel: "Start Caregiver Module 5",
      target: 3,
      unit: "module steps completed",
    },
  ],
  [
    "MILESTONE-FOUND-TRUSTED-SUPPORT",
    {
      href: "/resources#resource-diabetes-education-and-support",
      actionLabel: "Open the trusted support guide",
      target: 1,
      unit: "verified guide opened",
    },
  ],
  [
    "MILESTONE-PERSONAL-TOOLKIT",
    {
      href: "/milestones",
      actionLabel: "Explore milestone categories",
      target: 4,
      unit: "milestone categories explored",
    },
  ],
  [
    "MILESTONE-IN-YOUR-OWN-WORDS",
    {
      href: "/explain-it-back",
      actionLabel: "Explain a concept",
      target: 1,
      unit: "concept explained clearly",
    },
  ],
  [
    "MILESTONE-MEMORY-IN-MOTION",
    {
      href: "/explain-it-back?mode=spaced-review",
      actionLabel: "Start a Quick Review",
      target: 1,
      unit: "Quick Review completed",
    },
  ],
  [
    "MILESTONE-LABEL-WISE",
    {
      href: "/decode-the-label",
      actionLabel: "Decode a food label",
      target: 1,
      unit: "label exercise completed",
    },
  ],
  [
    "MILESTONE-STORY-EXPLORER",
    {
      href: "/stories",
      actionLabel: "Choose an interactive story",
      target: 1,
      unit: "interactive story completed",
    },
  ],
  [
    "MILESTONE-CONCEPTS-MADE-CLEAR",
    {
      href: "/explain-it-back",
      actionLabel: "Explain another concept",
      target: 3,
      unit: "distinct concepts explained clearly",
    },
  ],
  [
    "MILESTONE-MANY-PERSPECTIVES",
    {
      href: "/stories",
      actionLabel: "Choose another interactive story",
      target: 4,
      unit: "distinct interactive stories completed",
    },
  ],
  [
    "MILESTONE-CIRCLE-OF-SUPPORT",
    {
      href: "/caregiver",
      actionLabel: "Continue the Caregiver Pathway",
      target: 5,
      unit: "caregiver modules completed",
    },
  ],
  [
    "MILESTONE-RESOURCE-NAVIGATOR",
    {
      href: "/resources",
      actionLabel: "Explore trusted resources",
      target: 3,
      unit: "distinct verified guides opened",
    },
  ],
]);

export const milestoneCategoryLabels: Record<MilestoneCategory, string> = {
  learning: "Learning",
  understanding: "Understanding",
  appointment: "Appointment Preparation",
  support: "Support",
  resources: "Trusted Resources",
  toolkit: "Toolkit",
};

export const foundationJourneyLessonIds = Array.from(
  { length: 14 },
  (_, index) => `30000000-0000-0000-0000-${String(index + 1).padStart(12, "0")}`,
);
